/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: NORBERTO-3D (https://sketchfab.com/norberto3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/phoenix-bird-844ba0cf144a413ea92c779f18912042
Title: phoenix bird
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import phoenix_bird from '../assets/3D/phoenix_bird.glb'

const Bird = ({isRotating, ...props}) => {
  const birdRef = useRef()
  const { scene, animations } = useGLTF(phoenix_bird)
  const { actions } = useAnimations(animations, birdRef);

  return (
    <mesh {...props}>
      <primitive object={scene}/>
    </mesh>

  )
}

export default Bird;

